# -*- coding: utf-8 -*-
"""rawcnnagu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_-iTD7oDIpLTs-rWfuTJDonEfkPokwHU
"""

import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torch.optim import Adam
import torchvision
import torchvision.transforms.v2 as transforms

train_set = torchvision.datasets.MNIST("./data/", train=True, download=True)
valid_set = torchvision.datasets.MNIST("./data/", train=False, download=True)

trans=transforms.Compose([
    transforms.RandomRotation(degrees=15),
    transforms.RandomAffine(degrees=0, translate=(0.1, 0.1), scale=(0.9, 1.1)),
    transforms.ToImage(),
    transforms.ToDtype(torch.float32, scale=True)
])

train_set.transform = trans
valid_set.transform = trans

batch_size=128

train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=True)

test_loader = DataLoader(valid_set, batch_size=batch_size, shuffle=False)

class SimpleCNN(nn.Module):
    def __init__(self):
        super(SimpleCNN, self).__init__()
        self.features = nn.Sequential(
            nn.Conv2d(1, 32, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),
            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(2),
            nn.Flatten(),
            nn.Linear(64*7*7, 128),
            nn.ReLU(),
            nn.Linear(128, 10)
        )
    def forward(self, x):
        return self.features(x)

model = SimpleCNN()

from torch.nn.modules import loss
loss_fn = nn.CrossEntropyLoss()
optimizer = Adam(model.parameters(), lr=0.001)

epochs = 5

def train_model(model, train_loader, loss_fn, optimizer, epochs):
    model.train()
    for epoch in range(epochs):
        running_loss = 0.0
        for i, (images, labels) in enumerate(train_loader):
            optimizer.zero_grad()
            outputs = model(images)
            loss = loss_fn(outputs, labels)
            loss.backward()
            optimizer.step()
            running_loss += loss.item()
        print(f"Epoch {epoch+1}, Loss: {running_loss/len(train_loader):.4f}")

def evaluate_model(model, test_loader):
    model.eval()
    correct = 0
    total = 0
    with torch.no_grad():
        for images, labels in test_loader:
            outputs = model(images)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
    accuracy = 100 * correct / total
    print(f"Accuracy on the test set: {accuracy:.2f}%")
    return accuracy

"""Now, let's train the model using the defined functions."""

print("Starting training...")
train_model(model, train_loader, loss_fn, optimizer, epochs)
print("Training finished.")

"""After training, let's evaluate the model's performance on the test set."""

evaluate_model(model, test_loader)

"""Finally, I'll save the trained model's state dictionary. This allows you to load the trained weights later without needing to retrain the model."""

torch.save(model.state_dict(), 'mnist_cnn_model.pth')
print("Model saved to mnist_cnn_model.pth")









